name: SchoolMine
version: 1.0.0
main: com.schoolmine.SchoolMine
api-version: '1.21'
softdepend: [PlayerPoints]
authors: [school0107]
[cite_start]description: SchoolMine core plugin with advanced mining features. [cite: 53]

commands:
  schoolmine:
    [cite_start]description: Lenh quan tri admin. [cite: 67]
    permission: schoolmine.admin
  autopickup:
    [cite_start]description: Bat tat tu dong nhat do. [cite: 53]
    permission: schoolmine.autopickup
  autosmelt:
    [cite_start]description: Bat tat tu dong nung quang. [cite: 56]
    permission: schoolmine.autosmelt
  3x3:
    [cite_start]description: Bat tat che do dao 3x3. [cite: 55]
    permission: schoolmine.3x3
  automine:
    [cite_start]description: Bat tat che do tu dong dao. [cite: 57]
    permission: schoolmine.automine
  booster:
    [cite_start]description: Mo menu mua booster bang PlayerPoints. [cite: 60, 61]
    permission: schoolmine.booster
